{% set name = "attica" %}
{% set version = "5.67.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/attica-{{ version }}.tar.xz
  sha256: f4f3f6892287192deb61f38bab01c457d7950701f3e09c44a15809e7880ec3fa

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('attica', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Attica.so

about:
  home: https://api.kde.org/frameworks/attica/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Open Collaboration Service client library'
  description: |
    Attica is a Qt library that implements the Open Collaboration Services API version 1.6.
  dev_url: https://cgit.kde.org/attica.git/tree

extra:
  recipe-maintainers:
    - scopatz
