{% set name = "attica" %}
{% set version = "5.80.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/attica-{{ version }}.tar.xz
  sha256: e3aa866b01dfcdc1f59012c57f6bd49eabfe5d920560f766116a6633b394ce71

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('attica', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Attica.so

about:
  home: https://api.kde.org/frameworks/attica/html/index.html
  license: LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL
  license_family: GPL
  license_file:
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: Open Collaboration Service client library
  description: |
    Attica is a Qt library that implements the Open Collaboration Services API version 1.6.
  dev_url: https://cgit.kde.org/attica.git/tree

extra:
  recipe-maintainers:
    - scopatz
