travis:
  secure:
    BINSTAR_TOKEN: mvmZPemguM2ntXdDhhCJ7m6Q/sRgBLOv9Cl/+cbm+DORS8f9291vjQpAAoOvyETnt6SeY7t3m6AeUFzQK3eydD+5Mvqas/XYw24amDxEZn2bRx8D4CMjfOozadXxD+Ey992cc9Lsn0URKaVJHxxxsW0kLrYb4+HtvUasYcfmZitrq1vJG4zlWAhuwK1fQAYsYKZZkcacIE+bCofKJYOAgZrMiggcE3yoa11LzF2ZkW9pSK5p8sptIhlPpkjRcGnUlx3nhoBSJaiSBlaHvQi/w3vMMn1gTan386u6ypcjZNcOF24vIuGSCV6Dt0eehVbUbblNMmEAceqBSxIs+PvrD96MCPvfam7C/l65yDWH6YY75ZkHzKkSDt0+Q982nqH3MuR2OR/gIlCktBTxH7N1D0lARntviH5ANtZkaN3kgBUD3lSjx1xd7tEA9ibNnvfsLAvMfhQ6vyarTZktMwm7qyphEf/f5xW/vt5+F7D5533luq0g1T/VljJGkFTQFPW8n5aU9LjSPDP4T646C2t01ivrSGDiFGXshA0toIaU9C+8lJ/cUg9JjIJ12TcVmpMLebw6fh/kMw0DxMCKFd9Xrf2xBk8X57d/hmAHrV0WZ1YXhkm/GYxEfP7pxoettUXNm2YSLgVzlLYWnCjKE7tfT8HCJqCyKaQtzyqKh4CG7YU=
conda_forge_output_validation: true
bot:
  check_solvable: true
